# Dockerfile-frontend

# Estágio 1: Build do Angular
FROM node:20-alpine AS build

WORKDIR /app

# Copia package.json e package-lock.json primeiro (cache de dependências)
COPY frontend/package*.json ./
RUN npm install

# Copia todo o código do frontend
COPY frontend/ ./
RUN npm run build -- --output-path=./dist --configuration=production

# Estágio 2: Servir com Nginx
FROM nginx:alpine

# Copia o build do Angular para o Nginx
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
