# Dockerfile-frontend

# Estágio 1: Build Angular
FROM node:20-alpine AS build

WORKDIR /app

# Copia package.json primeiro (cache de dependências)
COPY frontend/package*.json ./
RUN npm install

# Copia o resto do frontend
COPY frontend/ ./
RUN npm run build -- --output-path=./dist --configuration=production

# Estágio 2: Servir com Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
